export const GalleryPhotos = [
	{
		id: "1",
		name: "Capstone Competition 1",
		height: 250,
		src: "https://ik.imagekit.io/5ywj5edvn/capstone-competition-1.jpeg",
		hash: "LmCH1i%gROkC*0pIRPbItmbcV@bH",
	},
	{
		id: "2",
		name: "Capstone Competition 2",
		height: 150,
		src: "https://ik.imagekit.io/5ywj5edvn/capstone-competition-2.jpeg",
		hash: "LLB:]ED4TeSd.mVDT0k9XSs8R-bF",
	},
	{
		id: "3",
		name: "Capstone Competition 3",
		height: 225,
		vertical: true,
		src: "https://ik.imagekit.io/5ywj5edvn/capstone-competition-3.jpeg",
		hash: "LgGut4.8kqV[_M%go}xax]t8j]a#",
	},
	{
		id: "4",
		name: "Capstone Competition 4",
		height: 300,
		src: "https://ik.imagekit.io/5ywj5edvn/capstone-competition-4.jpeg",
		hash: "LBG*TW~U00IA^+0#IBD*.RTJM{Io",
	},
	{
		id: "5",
		name: "Capstone Competition 5",
		height: 200,
		src: "https://ik.imagekit.io/5ywj5edvn/capstone-competition-5.jpeg",
		hash: "L6DSak5I02K9.A^+4.-U00M]=;Dh",
	},
	{
		id: "6",
		name: "Capstone Competition 6",
		height: 175,
		src: "https://ik.imagekit.io/5ywj5edvn/capstone-competition-6.jpeg",
		hash: "LHF#w803H=~8.SMyng-UI-M{Nyb_",
	},
	{
		id: "7",
		name: "Capstone Competition 7",
		height: 200,
		src: "https://ik.imagekit.io/5ywj5edvn/capstone-competition-7.jpeg",
		hash: "LFDu;^T14;a~~4IUkCs+r:M_xtf+",
	},
	{
		id: "8",
		name: "Capstone Competition 8",
		height: 225,
		src: "https://ik.imagekit.io/5ywj5edvn/capstone-competition-8.jpeg",
		hash: "L8Du*v^M00IA^+E357R*00R*~p-;",
	},
	{
		id: "9",
		name: "Capstone Competition 9",
		height: 200,
		src: "https://ik.imagekit.io/5ywj5edvn/capstone-competition-9.jpeg",
		hash: "LFEU[P#SIBxE~WaKM|IpW8EM%MR*",
	},
];
